<div style={{width: '100%', height: '100%', position: 'relative', background: 'white', overflow: 'hidden'}}>
    <div style={{width: 233.44, height: 54.14, paddingTop: 17.64, paddingBottom: 17.64, paddingLeft: 29.81, paddingRight: 29.20, left: 1358.90, top: 146.74, position: 'absolute', transform: 'rotate(11deg)', transformOrigin: 'top left', background: 'black', overflow: 'hidden', borderRadius: 30, justifyContent: 'center', alignItems: 'center', gap: 6.08, display: 'inline-flex'}}>
        <div style={{textAlign: 'center', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 26, fontFamily: 'Neue Montreal', fontWeight: '500', wordWrap: 'break-word'}}>Tools</div>
    </div>
    <div style={{width: 1091.70, height: 162, left: 318, top: 75, position: 'absolute', overflow: 'hidden'}}>
        <div style={{width: 178, height: 46, left: 457, top: 0, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 41, fontFamily: 'Inter', fontWeight: '500', wordWrap: 'break-word'}}>I can do</div>
        <div style={{width: 1091.70, height: 157, left: 0, top: 5, position: 'absolute', textAlign: 'center', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'black', fontSize: 164.30, fontFamily: 'Playfair Display', fontStyle: 'italic', fontWeight: '500', wordWrap: 'break-word'}}>Wonders</div>
    </div>
    <div style={{width: 853, left: 438, top: 766, position: 'absolute', flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'center', gap: 38, display: 'inline-flex'}}>
        <div style={{alignSelf: 'stretch', height: 54, textAlign: 'center', color: 'black', fontSize: 22, fontFamily: 'Inter', fontWeight: '500', wordWrap: 'break-word'}}>Figma ipsum component variant main layer. Export stroke editor undo plugin strikethrough share group.</div>
        <div style={{width: 268.93, height: 54.14, paddingTop: 17.64, paddingBottom: 17.64, paddingLeft: 29.81, paddingRight: 29.20, background: 'black', overflow: 'hidden', borderRadius: 30, justifyContent: 'center', alignItems: 'center', gap: 6.08, display: 'inline-flex'}}>
            <div style={{textAlign: 'center', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 21.46, fontFamily: 'Neue Montreal', fontWeight: '500', wordWrap: 'break-word'}}>Let’s talk</div>
        </div>
    </div>
    <div style={{width: 239.01, height: 61, paddingTop: 17.64, paddingBottom: 17.64, paddingLeft: 29.81, paddingRight: 29.20, left: 189.52, top: 177.79, position: 'absolute', transform: 'rotate(-11deg)', transformOrigin: 'top left', background: 'rgba(249, 103, 14, 0.89)', overflow: 'hidden', borderRadius: 60, justifyContent: 'center', alignItems: 'center', gap: 6.08, display: 'inline-flex'}}>
        <div style={{textAlign: 'center', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 26, fontFamily: 'Neue Montreal', fontWeight: '500', wordWrap: 'break-word'}}>Skills</div>
    </div>
    <div style={{width: 1483.17, height: 539.25, left: 122, top: 215, position: 'absolute'}}>
        <div style={{width: 345.67, height: 361.02, left: 0.70, top: 126.23, position: 'absolute', transform: 'rotate(-10deg)', transformOrigin: 'top left', background: '#D9D9D9', borderRadius: 9.88}}>
            <div style={{left: 74.42, top: 302.22, position: 'absolute', textAlign: 'center', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'black', fontSize: 31.60, fontFamily: 'Neue Montreal', fontWeight: '500', wordWrap: 'break-word'}}>Skills</div>
            <div style={{left: 81.20, top: 343.18, position: 'absolute', textAlign: 'center', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: '#F9670E', fontSize: 31.60, fontFamily: 'Playfair Display', fontStyle: 'italic', fontWeight: '500', wordWrap: 'break-word'}}>and</div>
            <div style={{left: 153.44, top: 330.11, position: 'absolute', textAlign: 'center', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'black', fontSize: 31.60, fontFamily: 'Neue Montreal', fontWeight: '500', wordWrap: 'break-word'}}>Tools</div>
            <img style={{width: 347.64, height: 262.87, left: 19.16, top: 29.65, position: 'absolute', background: 'linear-gradient(0deg, rgba(0, 0, 0, 0.16) 0%, rgba(0, 0, 0, 0.16) 100%)', boxShadow: '4.001184463500977px 4.001184463500977px 4.001184463500977px ', filter: 'blur(2px)', backdropFilter: 'blur(1.82px)'}} src="https://placehold.co/348x263" />
        </div>
        <div style={{width: 398.30, height: 365.56, left: 157.01, top: 109.52, position: 'absolute', transform: 'rotate(-6deg)', transformOrigin: 'top left', overflow: 'hidden', borderRadius: 31.41, outline: '1.75px rgba(0, 0, 0, 0.08) solid', outlineOffset: '-1.75px'}}>
            <div style={{width: 823, height: 823, left: 0, top: -36.09, position: 'absolute', background: 'linear-gradient(180deg, #1D1D1D 0%, black 95%)'}} />
            <div style={{left: 137.70, top: 52.35, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 40.82, fontFamily: 'SF Pro', fontWeight: '590', letterSpacing: 0.82, wordWrap: 'break-word'}}>Figma</div>
            <div style={{left: 143.49, top: 100.22, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 27.99, fontFamily: 'SF Pro', fontWeight: '400', wordWrap: 'break-word'}}>UI/UX Designing</div>
            <div style={{width: 66.99, height: 93, left: 35.49, top: 68.71, position: 'absolute', boxShadow: '1.1664056777954102px -1.1664056777954102px 9.214605331420898px white inset', overflow: 'hidden'}}>
                <div style={{width: 66.31, height: 92.06, left: 0.34, top: 0.47, position: 'absolute'}} />
                <div style={{width: 31.67, height: 31.67, left: 32.01, top: 29.18, position: 'absolute', background: '#1ABCFE'}} />
                <div style={{width: 31.67, height: 31.67, left: 6.27, top: 60.86, position: 'absolute', background: '#0ACF83'}} />
                <div style={{width: 31.67, height: 31.67, left: 29.05, top: 0.47, position: 'absolute', background: '#FF7262'}} />
                <div style={{width: 31.67, height: 31.67, left: 0.34, top: 3.44, position: 'absolute', background: '#F24E1E'}} />
                <div style={{width: 31.67, height: 31.67, left: 3.30, top: 32.15, position: 'absolute', background: '#A259FF'}} />
            </div>
            <div style={{width: 328.58, height: 131.44, left: 47.34, top: 156.73, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 16.37, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 19.63, wordWrap: 'break-word'}}>Figma ipsum component variant main layer. Undo inspect text rotate figjam comment opacity team slice device. Plugin editor invite mask clip subtract. Bullet figjam library pixel layer object. </div>
            <div style={{width: 148.22, height: 31.40, left: 60.21, top: 299.28, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>4+ Years of experience</div>
            <div style={{width: 148.22, height: 31.40, left: 62.92, top: 325.52, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>20 Personal Projects</div>
        </div>
        <div style={{width: 321.91, height: 442.77, left: 364.45, top: 50.19, position: 'absolute', transform: 'rotate(-7deg)', transformOrigin: 'top left', background: 'white', overflow: 'hidden', borderRadius: 26.37, outline: '0.91px #8A8A8A solid', outlineOffset: '-0.91px'}}>
            <div style={{width: 358.28, height: 463.59, left: 6.98, top: 6.30, position: 'absolute', overflow: 'hidden', borderRadius: 18.19, backgroundImage: 'url(https://placehold.co/358x464)'}}>
                <div style={{width: 277.82, height: 112.34, left: 24.10, top: 74.07, position: 'absolute', color: '#8C8B90', fontSize: 16.37, fontFamily: 'Neue Montreal', fontWeight: '400', wordWrap: 'break-word'}}>Figma ipsum component variant main layer. Group layer opacity auto asset share align effect arrow. Ellipse underline create scrolling italic. Opacity.</div>
                <div style={{width: 237.95, height: 32.66, left: 82.51, top: 401.29, position: 'absolute', background: '#5A5A5A', borderRadius: 117.30}} />
                <div style={{width: 147.13, height: 21.51, left: 82.51, top: 412.44, position: 'absolute', background: '#66D46D', borderRadius: 117.30}} />
                <div style={{width: 279.07, left: 19.67, top: 37.08, position: 'absolute', color: 'black', fontSize: 25.92, fontFamily: 'Neue Montreal', fontWeight: '500', wordWrap: 'break-word'}}>Mobile App development</div>
                <div style={{width: 148.21, height: 34.20, left: 129.98, top: 415.03, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>4+ Years of experience</div>
                <div style={{width: 148.21, height: 34.20, left: 35.51, top: 182, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'black', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>Flutter &amp; Dart</div>
                <div style={{width: 148.21, height: 34.20, left: 38.06, top: 202.76, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'black', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>Full app design</div>
            </div>
        </div>
        <div style={{width: 321.91, height: 442.77, left: 554.37, top: 3.49, position: 'absolute', transform: 'rotate(-1deg)', transformOrigin: 'top left', background: 'white', overflow: 'hidden', borderRadius: 26.37, outline: '0.91px #8A8A8A solid', outlineOffset: '-0.91px'}}>
            <div style={{width: 312.68, height: 432.37, left: 6.42, top: 5.53, position: 'absolute', overflow: 'hidden', borderRadius: 18.19, backgroundImage: 'url(https://placehold.co/313x432)'}}>
                <div style={{width: 270.89, height: 82.80, left: 16.20, top: 72.07, position: 'absolute', color: '#8C8B90', fontSize: 16.37, fontFamily: 'Neue Montreal', fontWeight: '400', wordWrap: 'break-word'}}>Figma ipsum component variant main layer. Group layer opacity auto asset share align effect arrow. Ellipse underline create scrolling italic. Opacity.</div>
                <div style={{width: 239.33, height: 5.98, left: 38.14, top: 400.35, position: 'absolute', background: '#5A5A5A', borderRadius: 117.30}} />
                <div style={{width: 147.83, height: 5.04, left: 38.14, top: 401.29, position: 'absolute', background: '#66D46D', borderRadius: 117.30}} />
                <div style={{width: 277.66, left: 15.82, top: 35.62, position: 'absolute', color: 'black', fontSize: 25.92, fontFamily: 'Neue Montreal', fontWeight: '500', wordWrap: 'break-word'}}>Software engineering</div>
                <div style={{width: 147.48, height: 17.88, left: 85.02, top: 409.11, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>4+ Years of experience</div>
                <div style={{width: 147.48, height: 17.88, left: 17.16, top: 166.99, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'black', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>Python</div>
                <div style={{width: 147.48, height: 17.88, left: 17.38, top: 187.91, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'black', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>Full stack</div>
            </div>
        </div>
        <div style={{width: 398.30, height: 401.94, left: 732.20, top: 35.18, position: 'absolute', transform: 'rotate(5deg)', transformOrigin: 'top left', overflow: 'hidden', borderRadius: 31.41, outline: '1.75px rgba(0, 0, 0, 0.08) solid', outlineOffset: '-1.75px'}}>
            <div style={{width: 812.39, height: 812.39, left: -30.28, top: 0, position: 'absolute', background: 'linear-gradient(180deg, #F9670E 0%, black 95%)'}} />
            <div style={{left: 161.61, top: 47.94, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 40.82, fontFamily: 'SF Pro', fontWeight: '590', letterSpacing: 0.82, wordWrap: 'break-word'}}>Notion</div>
            <div style={{left: 158.02, top: 105.02, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 27.99, fontFamily: 'SF Pro', fontWeight: '400', wordWrap: 'break-word'}}>Project Management</div>
            <div style={{width: 327.50, height: 126.59, left: 44.76, top: 154.96, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 16.37, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 19.63, wordWrap: 'break-word'}}>Figma ipsum component variant main layer. Undo inspect text rotate figjam comment opacity team slice device. Plugin editor invite mask clip subtract. Bullet figjam library pixel layer object. </div>
            <div style={{width: 148.18, height: 29.12, left: 41.04, top: 279.98, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>4+ Years of experience</div>
            <div style={{width: 148.18, height: 29.12, left: 38.75, top: 306.25, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>20 Personal Projects</div>
            <div style={{width: 68.34, height: 9, left: 65.16, top: 51.61, position: 'absolute', transform: 'rotate(-4deg)', transformOrigin: 'top left', background: 'white'}} />
            <div style={{width: 63.01, height: 56.45, left: 70.84, top: 66.42, position: 'absolute', transform: 'rotate(-4deg)', transformOrigin: 'top left', background: 'white'}} />
            <div style={{width: 86.44, height: 89.36, left: 56.11, top: 39.99, position: 'absolute', background: 'black'}} />
        </div>
        <div style={{width: 321.91, height: 442.77, left: 981.96, top: 21.50, position: 'absolute', transform: 'rotate(11deg)', transformOrigin: 'top left', background: 'white', overflow: 'hidden', borderRadius: 26.37, outline: '0.91px #8A8A8A solid', outlineOffset: '-0.91px'}}>
            <div style={{width: 381.84, height: 478.52, left: 7.74, top: 6.53, position: 'absolute', overflow: 'hidden', borderRadius: 18.19, backgroundImage: 'url(https://placehold.co/382x479)'}}>
                <div style={{width: 280.18, height: 128.25, left: 66.12, top: 73.46, position: 'absolute', color: '#8C8B90', fontSize: 16.37, fontFamily: 'Neue Montreal', fontWeight: '400', wordWrap: 'break-word'}}>Figma ipsum component variant main layer. Group layer opacity auto asset share align effect arrow. Ellipse underline create scrolling italic. Opacity.</div>
                <div style={{width: 235.88, height: 47.40, left: 38.16, top: 399.45, position: 'absolute', background: '#5A5A5A', borderRadius: 117.30}} />
                <div style={{width: 145.94, height: 30.60, left: 38.16, top: 399.45, position: 'absolute', background: '#66D46D', borderRadius: 117.30}} />
                <div style={{width: 278.33, left: 81.80, top: 37.70, position: 'absolute', color: 'black', fontSize: 25.92, fontFamily: 'Neue Montreal', fontWeight: '500', wordWrap: 'break-word'}}>Software engineering</div>
                <div style={{width: 147.82, height: 43.14, left: 80.28, top: 416.20, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>4+ Years of experience</div>
                <div style={{width: 147.82, height: 43.14, left: 60.61, top: 165.53, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'black', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>Python</div>
                <div style={{width: 147.82, height: 43.14, left: 56.77, top: 186.09, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'black', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>Full stack</div>
            </div>
        </div>
        <div style={{width: 398.30, height: 365.56, left: 1100.07, top: 76.39, position: 'absolute', transform: 'rotate(16deg)', transformOrigin: 'top left', overflow: 'hidden', borderRadius: 31.41, outline: '1.75px rgba(0, 0, 0, 0.08) solid', outlineOffset: '-1.75px'}}>
            <div style={{width: 929.11, height: 929.11, left: -107, top: 0, position: 'absolute', background: 'linear-gradient(180deg, #5B5B5B 0%, black 95%)'}} />
            <div style={{left: 207.25, top: 72.40, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 40.82, fontFamily: 'SF Pro', fontWeight: '590', letterSpacing: 0.82, wordWrap: 'break-word'}}>Notion</div>
            <div style={{left: 195.76, top: 127.42, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 27.99, fontFamily: 'SF Pro', fontWeight: '400', wordWrap: 'break-word'}}>Project Management</div>
            <div style={{width: 335.03, height: 184.29, left: 62.21, top: 155.59, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 16.37, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 19.63, wordWrap: 'break-word'}}>Figma ipsum component variant main layer. Undo inspect text rotate figjam comment opacity team slice device. Plugin editor invite mask clip subtract. Bullet figjam library pixel layer object. </div>
            <div style={{width: 146.05, height: 56.72, left: 50.31, top: 276.13, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>4+ Years of experience</div>
            <div style={{width: 146.05, height: 56.72, left: 42.97, top: 301.46, position: 'absolute', justifyContent: 'center', display: 'flex', flexDirection: 'column', color: 'white', fontSize: 14.55, fontFamily: 'Neue Montreal', fontWeight: '500', lineHeight: 17.45, wordWrap: 'break-word'}}>20 Personal Projects</div>
            <div style={{width: 68.07, height: 22.12, left: 119.99, top: 56.55, position: 'absolute', transform: 'rotate(-4deg)', transformOrigin: 'top left', background: 'white'}} />
            <div style={{width: 71.34, height: 67.69, left: 113.87, top: 72.76, position: 'absolute', transform: 'rotate(-4deg)', transformOrigin: 'top left', background: 'white'}} />
            <div style={{width: 97.35, height: 94.43, left: 101.80, top: 41.48, position: 'absolute', background: 'black'}} />
        </div>
    </div>
</div>